name: example-environment
channels:
  - ioam
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - partd
  - bokeh
  - dask
  - pandas
  - colorcet
  - geoviews
  - holoviews
  - datashader
  - xarray